<?php 
define("DB_HOST","localhost");
//define("DB_USER","kypai");
//define("DB_PWD","szc743712");
//define("DB_DBNAME","kypai");
define("DB_USER","root");
define("DB_PWD","helloworld");
define("DB_DBNAME","zp");
define("DB_CHARSET","utf8");
